# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'B:\form1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import QLabel, pyqtSignal,QObject,QEvent,QFileDialog,QPixmap
import sys
import  json
from a import run as Run_a
import tkinter.filedialog as fd

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(726, 386)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 731, 391))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setIconSize(QtCore.QSize(100, 100))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(20, 10, 581, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setStyleSheet("border:0")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(15, 352, 100, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setEnabled(True)
        self.lineEdit_2.setGeometry(QtCore.QRect(446, 357, 150, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(310, 360, 130, 13))
        self.label_3.setObjectName("label_3")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(20, 55, 581, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plainTextEdit_4.setFont(font)
        self.plainTextEdit_4.setStyleSheet("border:0")
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(20, 115, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plainTextEdit_5.setFont(font)
        self.plainTextEdit_5.setStyleSheet("border:0")
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_6.setGeometry(QtCore.QRect(20, 160, 111, 121))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plainTextEdit_6.setFont(font)
        self.plainTextEdit_6.setStyleSheet("border:0")
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.plainTextEdit_7 = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_7.setGeometry(QtCore.QRect(170, 160, 111, 121))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plainTextEdit_7.setFont(font)
        self.plainTextEdit_7.setStyleSheet("border:0")
        self.plainTextEdit_7.setObjectName("plainTextEdit_7")
        self.plainTextEdit_8 = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_8.setGeometry(QtCore.QRect(170, 115, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plainTextEdit_8.setFont(font)
        self.plainTextEdit_8.setStyleSheet("border:0")
        self.plainTextEdit_8.setObjectName("plainTextEdit_8")
        self.plainTextEdit_9 = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_9.setGeometry(QtCore.QRect(330, 160, 111, 121))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plainTextEdit_9.setFont(font)
        self.plainTextEdit_9.setStyleSheet("border:0")
        self.plainTextEdit_9.setObjectName("plainTextEdit_9")
        self.plainTextEdit_10 = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_10.setGeometry(QtCore.QRect(330, 115, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plainTextEdit_10.setFont(font)
        self.plainTextEdit_10.setStyleSheet("border:0")
        self.plainTextEdit_10.setObjectName("plainTextEdit_10")
        self.plainTextEdit_11 = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_11.setGeometry(QtCore.QRect(490, 160, 111, 121))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plainTextEdit_11.setFont(font)
        self.plainTextEdit_11.setStyleSheet("border:0")
        self.plainTextEdit_11.setObjectName("plainTextEdit_11")
        self.plainTextEdit_12 = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_12.setGeometry(QtCore.QRect(490, 115, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plainTextEdit_12.setFont(font)
        self.plainTextEdit_12.setStyleSheet("border:0")
        self.plainTextEdit_12.setObjectName("plainTextEdit_12")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("B:\\python-programm/qt/static/img/1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab,icon, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(16, 20, 580, 121))
        self.label.setStyleSheet("border: 1px solid #999;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_3)
        self.plainTextEdit.setGeometry(QtCore.QRect(15, 220, 581, 121))
        self.plainTextEdit.setStyleSheet("border:0")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_2.setGeometry(QtCore.QRect(15, 350, 100, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(310, 358, 130, 13))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(446, 355, 150, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.tab_3)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(15, 160, 581, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.plainTextEdit_3.setFont(font)
        self.plainTextEdit_3.setStyleSheet("border:0")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("B:\\python-programm/qt/static/img/2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3,icon1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(15, 352, 100, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit_3.setGeometry(QtCore.QRect(446, 357, 150, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(310, 360, 130, 13))
        self.label_4.setObjectName("label_4")
        self.plainTextEdit_13 = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_13.setGeometry(QtCore.QRect(20, 5, 581, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.plainTextEdit_13.setFont(font)
        self.plainTextEdit_13.setStyleSheet("border:0;")
        self.plainTextEdit_13.setObjectName("plainTextEdit_13")
        self.plainTextEdit_14 = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_14.setGeometry(QtCore.QRect(20, 50, 581, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plainTextEdit_14.setFont(font)
        self.plainTextEdit_14.setStyleSheet("border:0")
        self.plainTextEdit_14.setObjectName("plainTextEdit_14")
        self.plainTextEdit_15 = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_15.setGeometry(QtCore.QRect(20, 165, 111, 121))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plainTextEdit_15.setFont(font)
        self.plainTextEdit_15.setStyleSheet("border:0")
        self.plainTextEdit_15.setObjectName("plainTextEdit_15")
        self.plainTextEdit_16 = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_16.setGeometry(QtCore.QRect(330, 120, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plainTextEdit_16.setFont(font)
        self.plainTextEdit_16.setStyleSheet("border:0")
        self.plainTextEdit_16.setObjectName("plainTextEdit_16")
        self.plainTextEdit_17 = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_17.setGeometry(QtCore.QRect(330, 165, 111, 121))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plainTextEdit_17.setFont(font)
        self.plainTextEdit_17.setStyleSheet("border:0")
        self.plainTextEdit_17.setObjectName("plainTextEdit_17")
        self.plainTextEdit_18 = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_18.setGeometry(QtCore.QRect(20, 120, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plainTextEdit_18.setFont(font)
        self.plainTextEdit_18.setStyleSheet("border:0")
        self.plainTextEdit_18.setObjectName("plainTextEdit_18")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(150, 120, 151, 166))
        self.label_5.setStyleSheet("border: 1px solid #999;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(450, 120, 151, 166))
        self.label_6.setStyleSheet("border: 1px solid #999;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("B:\\python-programm/qt/static/img/3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2,icon2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lending"))
        self.plainTextEdit_2.setPlainText(_translate("MainWindow", "Добавьте заголовок"))
        self.pushButton_3.setText(_translate("MainWindow", "Создать"))
        self.lineEdit_2.setText(_translate("MainWindow", "127.0.0.1:2000"))
        self.label_3.setText(_translate("MainWindow", "Локальный адрес сайта"))
        self.plainTextEdit_4.setPlainText(_translate("MainWindow", "Добавьте текст"))
        self.plainTextEdit_5.setPlainText(_translate("MainWindow", "Добавьте подзаголовок"))
        self.plainTextEdit_6.setPlainText(_translate("MainWindow", "Добавьте текст"))
        self.plainTextEdit_7.setPlainText(_translate("MainWindow", "Добавьте текст"))
        self.plainTextEdit_8.setPlainText(_translate("MainWindow", "Добавьте подзаголовок"))
        self.plainTextEdit_9.setPlainText(_translate("MainWindow", "Добавьте текст"))
        self.plainTextEdit_10.setPlainText(_translate("MainWindow", "Добавьте подзаголовок"))
        self.plainTextEdit_11.setPlainText(_translate("MainWindow", "Добавьте текст"))
        self.plainTextEdit_12.setPlainText(_translate("MainWindow", "Добавьте подзаголовок"))
        self.label.setText(_translate("MainWindow", "Добавьте картинку"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Добавьте текст"))
        self.pushButton_2.setText(_translate("MainWindow", "Создать"))
        self.label_2.setText(_translate("MainWindow", "Локальный адрес сайта"))
        self.lineEdit.setText(_translate("MainWindow", "127.0.0.2:2000"))
        self.plainTextEdit_3.setPlainText(_translate("MainWindow", "Добавьте заголовок"))
        self.pushButton_5.setText(_translate("MainWindow", "Создать"))
        self.lineEdit_3.setText(_translate("MainWindow", "127.0.0.3:2000"))
        self.label_4.setText(_translate("MainWindow", "Локальный адрес сайта"))
        self.plainTextEdit_13.setPlainText(_translate("MainWindow", "Добавьте заголовок"))
        self.plainTextEdit_14.setPlainText(_translate("MainWindow", "Добавьте текст"))
        self.plainTextEdit_15.setPlainText(_translate("MainWindow", "Добавьте текст"))
        self.plainTextEdit_16.setPlainText(_translate("MainWindow", "Добавьте подзаголовок"))
        self.plainTextEdit_17.setPlainText(_translate("MainWindow", "Добавьте текст"))
        self.plainTextEdit_18.setPlainText(_translate("MainWindow", "Добавьте подзаголовок"))
        self.label_5.setText(_translate("MainWindow", "Добавьте картинку"))
        self.label_6.setText(_translate("MainWindow", "Добавьте картинку"))


class MyWin(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()

        self.ui = Ui_MainWindow()  # Экземпляр класса Ui_MainWindow, в нем конструктор всего GUI.
        self.ui.setupUi(self)  # Инициализация GUI
        self.ui.pushButton_3.clicked.connect(self.Save1)
        self.ui.pushButton_2.clicked.connect(self.Save2)
        self.ui.pushButton_5.clicked.connect(self.Save3)
        clickable(self.ui.label).connect(self.open_file1)
        clickable(self.ui.label_5).connect(self.open_file2)
        clickable(self.ui.label_6).connect(self.open_file3)

    def open_file1(self):
        filename = QFileDialog.getOpenFileName(self, "Открыть файл",'static/img/1.png','(*.jpg);;(*.png)')
        with open("config.json", "r") as f:
            dict = json.load(f)
            dict['SH2']['i21'] = filename[0].split("/")[-1]
            with open("config.json", "w") as s:
                 json.dump(dict,s,indent=4)
        self.ui.label.setPixmap(QPixmap(filename[0]))

    def open_file2(self):
        filename = QFileDialog.getOpenFileName(self, "Открыть файл",'static/img/1.png','(*.jpg);;(*.png)')
        with open("config.json", "r") as f:
            dict = json.load(f)
            dict['SH3']['i31'] = filename[0].split("/")[-1]
            with open("config.json", "w") as s:
                 json.dump(dict,s,indent=4)
        self.ui.label_5.setPixmap(QPixmap(filename[0]))

    def open_file3(self):
        filename = QFileDialog.getOpenFileName(self, "Открыть файл",'static/img/1.png','(*.jpg);;(*.png)')
        with open("config.json", "r") as f:
            dict = json.load(f)
            dict['SH3']['i32'] = filename[0].split("/")[-1]
            with open("config.json", "w") as s:
                 json.dump(dict,s,indent=4)
        self.ui.label_6.setPixmap(QPixmap(filename[0]))

    def Save1(self):
        with open("config.json", "r") as f:
            dict=json.load(f)
            dict['SH1']['z11'] = self.ui.plainTextEdit_2.toPlainText()
            dict['SH1']['t11'] = self.ui.plainTextEdit_4.toPlainText()
            dict['SH1']['z12'] = self.ui.plainTextEdit_5.toPlainText()
            dict['SH1']['t12'] = self.ui.plainTextEdit_6.toPlainText()
            dict['SH1']['z13'] = self.ui.plainTextEdit_8.toPlainText()
            dict['SH1']['t13'] = self.ui.plainTextEdit_7.toPlainText()
            dict['SH1']['z14'] = self.ui.plainTextEdit_10.toPlainText()
            dict['SH1']['t14'] = self.ui.plainTextEdit_9.toPlainText()
            dict['SH1']['z15'] = self.ui.plainTextEdit_12.toPlainText()
            dict['SH1']['t15'] = self.ui.plainTextEdit_11.toPlainText()
            with open("config.json", "w") as s:
                 json.dump(dict,s,indent=4)

    def Save2(self):
        with open("config.json", "r") as f:
            dict=json.load(f)
            dict['SH2']['z21'] = self.ui.plainTextEdit_2.toPlainText()
            dict['SH2']['t21'] = self.ui.plainTextEdit_4.toPlainText()
            with open("config.json", "w") as s:
                 json.dump(dict,s,indent=4)

    def Save3(self):
        with open("config.json", "r") as f:
            dict=json.load(f)
            dict['SH3']['z31'] = self.ui.plainTextEdit_13.toPlainText()
            dict['SH3']['t31'] = self.ui.plainTextEdit_14.toPlainText()
            dict['SH3']['z32'] = self.ui.plainTextEdit_18.toPlainText()
            dict['SH3']['t32'] = self.ui.plainTextEdit_15.toPlainText()
            dict['SH3']['z33'] = self.ui.plainTextEdit_16.toPlainText()
            dict['SH3']['t33'] = self.ui.plainTextEdit_17.toPlainText()
            with open("config.json", "w") as s:
                 json.dump(dict,s,indent=4)


def clickable(widget):
    class Filter(QObject):

        clicked = pyqtSignal()

        def eventFilter(self, obj, event):

            if obj == widget:
                if event.type() == QEvent.MouseButtonRelease:
                    if obj.rect().contains(event.pos()):
                        self.clicked.emit()
                        # The developer can opt for .emit(obj) to get the object within the slot.
                    return True

            return False

    filter = Filter(widget)
    widget.installEventFilter(filter)
    return filter.clicked



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = MyWin()
    window.show()
    sys.exit(app.exec_())
